import { defineConfig, envField, fontProviders } from 'astro/config';
import icon from 'astro-icon';
import mdx from '@astrojs/mdx';
import netlify from '@astrojs/netlify';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { loadEnv } from 'vite';

import { buildMigrate, buildSyncAllContent, buildSyncImages } from './src/db/sync/buildSync.ts';
import { logLevels } from './src/utils/logs/logger';

const modeArgIdx = process.argv.indexOf('--mode');
const mode =
  modeArgIdx !== -1 && process.argv[modeArgIdx + 1]
    ? process.argv[modeArgIdx + 1]
    : 'production';
const buildEnv = loadEnv(mode, process.cwd(), '');

// properties without "--DEFAULT--" either use a setting decided by me or/and didn't have a default value

// https://astro.build/config
export default defineConfig({
  // Resolves to the "./public" directory, relative to this config file
  site: 'https://duckycoding.dev',
  publicDir: './public', // --DEFAULT--
  srcDir: './src', // --DEFAULT--
  outDir: './dist', // --DEFAULT--
  base: '/',
  trailingSlash: 'ignore', // --DEFAULT--
  adapter: netlify({
    imageCDN: false,
  }),
  compressHTML: true, // could be set to false in development using env variables
  scopedStyleStrategy: 'attribute', // --DEFAULT--
  build: {
    format: 'directory', // --DEFAULT--
    server: '.server_javascript', // relative to outDir
    client: './client_javascript_and_css', // relative to outDir
    assets: '_astro', // assets generated by Astro
    redirects: true, // --DEFAULT--
    inlineStylesheets: 'auto', // --DEFAULT-- - if css is small it gets inlined, else a css file is created
    // assetsPrefix: '', // TODO, not sure how to use it
    // serverEntry: , // TODO, not sure how to use it
  },
  server: ({ command }) => ({
    port: command === 'dev' ? 4321 : 1234,
    // host: command === 'dev' ? false : false, // exposes port on local ip address in preview mode
    open: false,
    headers: {}, // --DEFAULT--
  }),
  devToolbar: {
    enabled: false,
  }, // --DEFAULT--
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'hover', // --DEFAULT--
  },
  image: {
    endpoint: undefined, // --DEFAULT--, TODO, not sure how to use it
    service: {
      entrypoint: 'astro/assets/services/sharp',
      config: {
        limitInputPixels: false,
      },
    },
    domains: [], // --DEFAULT-- = no remote images will be optimized, TODO: if hosting images, will need to set this
    remotePatterns: [], // --DEFAULT--, TODO: if hosting images, will need to set this
  },
  markdown: {
    syntaxHighlight: 'shiki', // --DEFAULT--
    // shikiConfig: , // TODO
    // remarkPlugins: , // TODO
    // rehypePlugins: , // TODO
    // remarkRehype: , // TODO
    gfm: true, // --DEFAULT--
    smartypants: true, // --DEFAULT--
    shikiConfig: {
      theme: 'github-dark-high-contrast',
      wrap: null,
    },
  },
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
    fallback: {
      // it: 'en', // when italian page is missing, redirects to /en
      // if no fallback is found, pages return 404
    },
    routing: {
      prefixDefaultLocale: false, // --DEFAULT-- TODO: need to check if this allows for english for both cases .../en/about and .../about, or only for the latter
      // redirectToDefaultLocale: false, // this only works with prefixDefaultLocale set to true: if that's the case, having this set to false we can have a different homepage, for example for asking the user to select the language they want to use
    },
  },
  vite: {
    css: {
      devSourcemap: true,
    },
    build: {
      // cssMinify: 'lightningcss',
      sourcemap: true,
    },
    plugins: [tailwindcss()],
  }, // add Vite configs TODO
  integrations: [
    {
      name: 'db-sync',
      hooks: {
        'astro:build:start': async ({ logger }) => {
          const dbConfig = {
            url: buildEnv['TURSO_DATABASE_URL'] ?? '',
            authToken: buildEnv['TURSO_AUTH_TOKEN'],
          };
          logger.info('Running DB migrations...');
          const migrateResult = await buildMigrate(dbConfig);
          if (!migrateResult.success) {
            logger.warn(`Migration warning: ${migrateResult.error}`);
          }
          logger.info('Starting DB sync...');
          await buildSyncImages(dbConfig);
          await buildSyncAllContent(dbConfig);
          logger.info('DB sync complete.');
        },
      },
    },
    mdx(),
    sitemap(),
    icon({
      iconDir: 'src/assets/icons', // user svgs stored in this path instead of src/icons
    }),
  ],
  fonts: [
    {
      provider: fontProviders.google(),
      name: 'Inter',
      cssVariable: '--font-inter',
      weights: ['100 900'],
      styles: ['normal', 'italic'],
    },
  ],
  experimental: {
    contentIntellisense: true,
  },
  env: {
    validateSecrets: true,
    schema: {
      BASE_SITE_URL: envField.string({
        context: 'client',
        access: 'public',
        url: true,
      }),
      SERVER_LOGS_LEVEL: envField.enum({
        context: 'server',
        access: 'public',
        values: logLevels,
        default: 'info',
      }),
      CLIENT_LOGS_LEVEL: envField.enum({
        context: 'client',
        access: 'public',
        values: logLevels,
        default: 'info',
      }),
      TURSO_DATABASE_URL: envField.string({
        context: 'server',
        access: 'secret',
        url: true,
      }),
      TURSO_AUTH_TOKEN: envField.string({
        context: 'server',
        access: 'secret',
        optional: true,
      }),
    },
  },
});
