import { defineConfig, envField, fontProviders } from 'astro/config';
import icon from 'astro-icon';
import mdx from '@astrojs/mdx';
import netlify from '@astrojs/netlify';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';

import { buildMigrate, buildSyncAllContent, buildSyncImages } from './src/db/sync/buildSync.ts';
import { logLevels } from './src/utils/logs/logger';

const modeArgIdx = process.argv.indexOf('--mode');
const mode =
  modeArgIdx !== -1 && process.argv[modeArgIdx + 1]
    ? process.argv[modeArgIdx + 1]
    : 'production';
const buildEnv = loadEnv(mode, process.cwd(), '');

// properties without "--DEFAULT--" either use a setting decided by me or/and didn't have a default value

// https://astro.build/config
export default defineConfig({
  // Resolves to the "./public" directory, relative to this config file
  site: 'https://duckycoding.dev',
  publicDir: './public', // --DEFAULT--
  srcDir: './src', // --DEFAULT--
  outDir: './dist', // --DEFAULT--
  base: '/',
  trailingSlash: 'ignore', // --DEFAULT--
  adapter: netlify({
    imageCDN: false,
  }),
  compressHTML: true, // could be set to false in development using env variables
  scopedStyleStrategy: 'attribute', // --DEFAULT--
  build: {
    format: 'directory', // --DEFAULT--
    server: '.server_javascript', // relative to outDir
    client: './client_javascript_and_css', // relative to outDir
    assets: '_astro', // assets generated by Astro
    redirects: true, // --DEFAULT--
    inlineStylesheets: 'auto', // --DEFAULT-- - if css is small it gets inlined, else a css file is created
    // assetsPrefix: '', // TODO, not sure how to use it
    // serverEntry: , // TODO, not sure how to use it
  },
  server: ({ command }) => ({
    port: command === 'dev' ? 4321 : 1234,
    // host: command === 'dev' ? false : false, // exposes port on local ip address in preview mode
    open: false,
    headers: {}, // --DEFAULT--
  }),
  devToolbar: {
    enabled: false,
  }, // --DEFAULT--
  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'hover', // --DEFAULT--
  },
  image: {
    endpoint: undefined, // --DEFAULT--, TODO, not sure how to use it
    service: {
      entrypoint: 'astro/assets/services/sharp',
      config: {
        limitInputPixels: false,
      },
    },
    domains: [], // --DEFAULT-- = no remote images will be optimized, TODO: if hosting images, will need to set this
    remotePatterns: [], // --DEFAULT--, TODO: if hosting images, will need to set this
  },
  markdown: {
    syntaxHighlight: 'shiki', // --DEFAULT--
    // shikiConfig: , // TODO
    // remarkPlugins: , // TODO
    // rehypePlugins: , // TODO
    // remarkRehype: , // TODO
    // gfm and smartypants are deprecated config keys as of Astro 7: they now
    // belong to the processor. Both were set to their default of true, and
    // Sätteri (the new default processor) applies GitHub-Flavored Markdown and
    // smart punctuation out of the box, so dropping them changes nothing.
    shikiConfig: {
      theme: 'github-dark-high-contrast',
      wrap: null,
    },
  },
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
    fallback: {
      // it: 'en', // when italian page is missing, redirects to /en
      // if no fallback is found, pages return 404
    },
    routing: {
      prefixDefaultLocale: false, // --DEFAULT-- TODO: need to check if this allows for english for both cases .../en/about and .../about, or only for the latter
      // redirectToDefaultLocale: false, // this only works with prefixDefaultLocale set to true: if that's the case, having this set to false we can have a different homepage, for example for asking the user to select the language they want to use
    },
  },
  vite: {
    // `@reference` is a Tailwind v4 directive, resolved by @tailwindcss/vite —
    // not by Astro or by Vite's own CSS @import handling. On Astro 6 + Vite 7
    // it resolved the tsconfig "paths" alias; on Astro 7 + Vite 8 it does not,
    // and the build fails with "Can't resolve '@styles/global.css'".
    //
    // Which layer regressed (Vite, Astro's alias plumbing, or the Tailwind
    // plugin) was NOT isolated. What is established: it is not the removal of
    // tsconfig "baseUrl" — the build fails with baseUrl restored too.
    //
    // Declaring the alias here fixes CSS resolution and leaves the
    // tsconfig-driven aliases used by JS/TS imports untouched. A relative
    // `@reference '../../styles/global.css'` also works and needs no config,
    // if this ever becomes more trouble than it is worth.
    //
    // Keep in sync with "paths" in tsconfig.json and the alias map in
    // vitest.config.ts — see CLEANUP-006.
    resolve: {
      alias: {
        '@styles': fileURLToPath(new URL('./src/styles', import.meta.url)),
      },
    },
    css: {
      devSourcemap: true,
    },
    build: {
      // cssMinify: 'lightningcss',
      sourcemap: true,
    },
    plugins: [tailwindcss()],
  }, // add Vite configs TODO
  integrations: [
    {
      name: 'db-sync',
      hooks: {
        'astro:build:start': async ({ logger }) => {
          // Every build migrates and rewrites the DB the loaded env points at.
          // `DB_SYNC=skip npm run astro:build:local` builds the site without
          // touching any database at all. Default stays 'run' so Netlify
          // production builds are unchanged.
          if ((buildEnv['DB_SYNC'] ?? 'run') === 'skip') {
            logger.info('DB_SYNC=skip — skipping migrations and content sync.');
            return;
          }

          const dbConfig = {
            url: buildEnv['TURSO_DATABASE_URL'] ?? '',
            authToken: buildEnv['TURSO_AUTH_TOKEN'],
          };
          logger.info('Running DB migrations...');
          const migrateResult = await buildMigrate(dbConfig);
          if (!migrateResult.success) {
            // Non-fatal: tables may already exist (e.g. drizzle-kit push).
            logger.warn(`Migration warning: ${migrateResult.error}`);
          }
          logger.info('Starting DB sync...');
          await buildSyncImages(dbConfig);
          const syncResult = await buildSyncAllContent(dbConfig);
          if (!syncResult.success) {
            // Abort rather than ship a build whose search index is half-written.
            throw new Error(`DB content sync failed: ${syncResult.error}`);
          }
          logger.info('DB sync complete.');
        },
      },
    },
    mdx(),
    sitemap(),
    // Every icon on the site comes from @iconify-json/mdi or @iconify-json/ph.
    // `iconDir` is deliberately not set: it previously pointed at
    // src/assets/icons, which does not exist. Set it only when local SVGs are
    // actually added, and create the directory in the same change.
    icon(),
  ],
  fonts: [
    {
      provider: fontProviders.google(),
      name: 'Inter',
      cssVariable: '--font-inter',
      weights: ['100 900'],
      styles: ['normal', 'italic'],
    },
  ],
  experimental: {
    contentIntellisense: true,
  },
  env: {
    validateSecrets: true,
    schema: {
      BASE_SITE_URL: envField.string({
        context: 'client',
        access: 'public',
        url: true,
      }),
      SERVER_LOGS_LEVEL: envField.enum({
        context: 'server',
        access: 'public',
        values: logLevels,
        default: 'info',
      }),
      CLIENT_LOGS_LEVEL: envField.enum({
        context: 'client',
        access: 'public',
        values: logLevels,
        default: 'info',
      }),
      TURSO_DATABASE_URL: envField.string({
        context: 'server',
        access: 'secret',
        url: true,
      }),
      TURSO_AUTH_TOKEN: envField.string({
        context: 'server',
        access: 'secret',
        optional: true,
      }),
      // Build-time only: 'skip' makes the db-sync integration a no-op, so a
      // build never migrates or rewrites the database it points at.
      DB_SYNC: envField.enum({
        context: 'server',
        access: 'public',
        values: ['run', 'skip'],
        default: 'run',
      }),
    },
  },
});
