DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS postsTags;
DROP TABLE IF EXISTS postsAuthors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS images;
