import { LayoutLocaleParams } from '@/types/Locales';
import { unstable_setRequestLocale } from 'next-intl/server';
import {notFound} from 'next/navigation';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'it'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default function RootLayout({
  children, params
}: LayoutLocaleParams) {
  // Validate that the incoming `locale` parameter is valid
  const {locale} = params;
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  unstable_setRequestLocale(locale);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}